import type { Prisma, MovieType } from '@prisma/client'

export const movies = (<const>{
  playing: [
    {
      title: 'Flash',
      duration: '1h 20 min',
      age: 12,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: '/images/posters/flash.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845448/nextflix/posters/flash.webp',
      trailerUrl: '/videos/flash.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849556/nextflix/videos/flash.mp4',
      videoUrl: '/videos/flash.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849556/nextflix/videos/flash.mp4',
    },
    {
      title: 'Los feos',
      duration: '2h 5 min',
      age: 12,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: '/images/posters/los-feos.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845467/nextflix/posters/los-feos.webp',
      trailerUrl: '/videos/los-feos.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850107/nextflix/videos/los-feos.mp4',
      videoUrl: '/videos/los-feos.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850107/nextflix/videos/los-feos.mp4',
    },
    {
      title: 'Karate Kid',
      duration: '1h 10 min',
      age: 0,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: '/images/posters/karate-kid.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845451/nextflix/posters/karate-kid.webp',
      trailerUrl: '/videos/karate-kid.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849977/nextflix/videos/karate-kid.mp4',
      videoUrl: '/videos/karate-kid.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849977/nextflix/videos/karate-kid.mp4',
    },
    {
      title: 'Super detective en Hollywood',
      duration: '2h 10 min',
      age: 0,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: '/images/posters/super-detective-en-hollywood.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845472/nextflix/posters/super-detective-en-hollywood.webp',
      trailerUrl: '/videos/super-detective-en-hollywood.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850223/nextflix/videos/super-detective-en-hollywood.mp4',
      videoUrl: '/videos/super-detective-en-hollywood.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850223/nextflix/videos/super-detective-en-hollywood.mp4',
    },
    {
      title: 'Fracture',
      duration: '1h 50 min',
      age: 18,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: '/images/posters/fracture.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845448/nextflix/posters/fracture.webp',
      trailerUrl: '/videos/fracture.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849654/nextflix/videos/fracture.mp4',
      videoUrl: '/videos/fracture.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849654/nextflix/videos/fracture.mp4',
    },
    {
      title: 'Spiderman',
      duration: '2h 30 min',
      age: 0,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: '/images/posters/spiderman.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845471/nextflix/posters/spiderman.webp',
      trailerUrl: '/videos/spiderman.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850241/nextflix/videos/spiderman.mp4',
      videoUrl: '/videos/spiderman.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850241/nextflix/videos/spiderman.mp4',
    },
    {
      title: 'Al filo del mañana',
      duration: '1h 35 min',
      age: 16,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: '/images/posters/al-filo-del-ma%C3%B1ana.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845447/nextflix/posters/al-filo-del-ma%C3%B1ana.webp',
      trailerUrl: '/videos/al-filo-del-ma%C3%B1ana.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849380/nextflix/videos/al-filo-del-ma%C3%B1ana.mp4',
      videoUrl: '/videos/al-filo-del-ma%C3%B1ana.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849380/nextflix/videos/al-filo-del-ma%C3%B1ana.mp4',
    },
    {
      title: 'Top Gun',
      duration: '2h 35 min',
      age: 18,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: '/images/posters/top-gun.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845473/nextflix/posters/top-gun.webp',
      trailerUrl: '/videos/top-gun.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850228/nextflix/videos/top-gun.mp4',
      videoUrl: '/videos/top-gun.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850228/nextflix/videos/top-gun.mp4',
    },
    {
      title: 'Jack Reacher',
      duration: '1h 50 min',
      age: 16,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: '/images/posters/jack-reacher.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845449/nextflix/posters/jack-reacher.webp',
      trailerUrl: '/videos/jack-reacher.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849862/nextflix/videos/jack-reacher.mp4',
      videoUrl: '/videos/jack-reacher.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849862/nextflix/videos/jack-reacher.mp4',
    },
    {
      title: 'Sonic',
      duration: '2h 05 min',
      age: 18,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: '/images/posters/sonic.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845470/nextflix/posters/sonic.webp',
      trailerUrl: '/videos/sonic.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850234/nextflix/videos/sonic.mp4',
      videoUrl: '/videos/sonic.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850234/nextflix/videos/sonic.mp4',
    },
  ],
  trending: [
    {
      title: 'La pareja perfecta',
      duration: '120 min',
      age: 16,
      genres: ['Action', 'Adventure'],
      type: 'trending',
      posterUrl: '/images/posters/la-pareja-perfecta.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845466/nextflix/posters/la-pareja-perfecta.webp',
      trailerUrl: '/videos/la-pareja-perfecta.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850087/nextflix/videos/la-pareja-perfecta.mp4',
      videoUrl: '/videos/la-pareja-perfecta.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850087/nextflix/videos/la-pareja-perfecta.mp4',
      rankingUrl: '/images/rankings/ranking1.webp',
      // rankingUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845553/nextflix/rankings/ranking1.webp',
    },
    {
      title: 'Respira',
      duration: '150 min',
      age: 12,
      genres: ['Drama', 'Thriller'],
      type: 'trending',
      posterUrl: '/images/posters/respira.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845469/nextflix/posters/respira.webp',
      trailerUrl: '/videos/respira.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850158/nextflix/videos/respira.mp4',
      videoUrl: '/videos/respira.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850158/nextflix/videos/respira.mp4',
      rankingUrl: '/images/rankings/ranking2.webp',
      // rankingUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845554/nextflix/rankings/ranking2.webp',
    },
    {
      title: 'Prison Break',
      duration: '90 min',
      age: 18,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: '/images/posters/prison-break.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845468/nextflix/posters/prison-break.webp',
      trailerUrl: '/videos/prison-break.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850137/nextflix/videos/prison-break.mp4',
      videoUrl: '/videos/prison-break.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745850137/nextflix/videos/prison-break.mp4',
      rankingUrl: '/images/rankings/ranking3.webp',
      // rankingUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845555/nextflix/rankings/ranking3.webp',
    },
    {
      title: 'KAOS',
      duration: '90 min',
      age: 0,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: '/images/posters/kaos.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845450/nextflix/posters/kaos.webp',
      trailerUrl: '/videos/kaos.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849949/nextflix/videos/kaos.mp4',
      videoUrl: '/videos/kaos.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849949/nextflix/videos/kaos.mp4',
      rankingUrl: '/images/rankings/ranking4.webp',
      // rankingUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845557/nextflix/rankings/ranking4.webp',
    },
    {
      title: 'Accidente',
      duration: '90 min',
      age: 12,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: '/images/posters/accidente.webp',
      // posterUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845446/nextflix/posters/accidente.webp',
      trailerUrl: '/videos/accidente.mp4',
      // trailerUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849329/nextflix/videos/accidente.mp4',
      videoUrl: '/videos/accidente.mp4',
      // videoUrl: 'https://res.cloudinary.com/devm5dl9j/video/upload/v1745849329/nextflix/videos/accidente.mp4',
      rankingUrl: '/images/rankings/ranking5.webp',
      // rankingUrl: 'https://res.cloudinary.com/devm5dl9j/image/upload/v1745845558/nextflix/rankings/ranking5.webp',
    },
  ],
}) satisfies Record<MovieType, Prisma.MovieCreateManyInput[]>

export const users = (<const>[
  { email: 'user1@example.com', password: 'Abc123*' },
  { email: 'user2@example.com', password: 'Xyz789*' },
]) satisfies Prisma.UserCreateManyInput[]
