import type { Prisma, MovieType } from '@prisma/client'

export const movies = (<const>{
  playing: [
    {
      title: 'Flash',
      duration: '1h 20 min',
      age: 12,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: 'nextflix/posters/flash',
      trailerUrl: 'nextflix/videos/flash',
      videoUrl: 'nextflix/videos/flash',
    },
    {
      title: 'Los feos',
      duration: '2h 5 min',
      age: 12,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: 'nextflix/posters/los-feos',
      trailerUrl: 'nextflix/videos/los-feos',
      videoUrl: 'nextflix/videos/los-feos',
    },
    {
      title: 'Karate Kid',
      duration: '1h 10 min',
      age: 0,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: 'nextflix/posters/karate-kid',
      trailerUrl: 'nextflix/videos/karate-kid',
      videoUrl: 'nextflix/videos/karate-kid',
    },
    {
      title: 'Super detective en Hollywood',
      duration: '2h 10 min',
      age: 0,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: 'nextflix/posters/super-detective-en-hollywood',
      trailerUrl: 'nextflix/videos/super-detective-en-hollywood',
      videoUrl: 'nextflix/videos/super-detective-en-hollywood',
    },
    {
      title: 'Fracture',
      duration: '1h 50 min',
      age: 18,
      genres: ['Drama', 'Family', 'Action'],
      type: 'playing',
      posterUrl: 'nextflix/posters/fracture',
      trailerUrl: 'nextflix/videos/fracture',
      videoUrl: 'nextflix/videos/fracture',
    },
    {
      title: 'Spiderman',
      duration: '2h 30 min',
      age: 0,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: 'nextflix/posters/spiderman',
      trailerUrl: 'nextflix/videos/spiderman',
      videoUrl: 'nextflix/videos/spiderman',
    },
    {
      title: 'Al filo del mañana',
      duration: '1h 35 min',
      age: 16,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: 'nextflix/posters/al-filo-del-mañana',
      trailerUrl: 'nextflix/videos/al-filo-del-mañana',
      videoUrl: 'nextflix/videos/al-filo-del-mañana',
    },
    {
      title: 'Top Gun',
      duration: '2h 35 min',
      age: 18,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: 'nextflix/posters/top-gun',
      trailerUrl: 'nextflix/videos/top-gun',
      videoUrl: 'nextflix/videos/top-gun',
    },
    {
      title: 'Jack Reacher',
      duration: '1h 50 min',
      age: 16,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: 'nextflix/posters/jack-reacher',
      trailerUrl: 'nextflix/videos/jack-reacher',
      videoUrl: 'nextflix/videos/jack-reacher',
    },
    {
      title: 'Sonic',
      duration: '2h 05 min',
      age: 18,
      genres: ['Action', 'Family', 'Marvel'],
      type: 'playing',
      posterUrl: 'nextflix/posters/sonic',
      trailerUrl: 'nextflix/videos/sonic',
      videoUrl: 'nextflix/videos/sonic',
    },
  ],
  trending: [
    {
      title: 'La pareja perfecta',
      duration: '120 min',
      age: 16,
      genres: ['Action', 'Adventure'],
      type: 'trending',
      posterUrl: 'nextflix/posters/la-pareja-perfecta',
      trailerUrl: 'nextflix/videos/la-pareja-perfecta',
      videoUrl: 'nextflix/videos/la-pareja-perfecta',
      rankingUrl: 'nextflix/rankings/ranking1',
    },
    {
      title: 'Respira',
      duration: '150 min',
      age: 12,
      genres: ['Drama', 'Thriller'],
      type: 'trending',
      posterUrl: 'nextflix/posters/respira',
      trailerUrl: 'nextflix/videos/respira',
      videoUrl: 'nextflix/videos/respira',
      rankingUrl: 'nextflix/rankings/ranking2',
    },
    {
      title: 'Prison Break',
      duration: '90 min',
      age: 18,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: 'nextflix/posters/prison-break',
      trailerUrl: 'nextflix/videos/prison-break',
      videoUrl: 'nextflix/videos/prison-break',
      rankingUrl: 'nextflix/rankings/ranking3',
    },
    {
      title: 'KAOS',
      duration: '90 min',
      age: 0,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: 'nextflix/posters/kaos',
      trailerUrl: 'nextflix/videos/kaos',
      videoUrl: 'nextflix/videos/kaos',
      rankingUrl: 'nextflix/rankings/ranking4',
    },
    {
      title: 'Accidente',
      duration: '90 min',
      age: 12,
      genres: ['Comedy', 'Family'],
      type: 'trending',
      posterUrl: 'nextflix/posters/accidente',
      trailerUrl: 'nextflix/videos/accidente',
      videoUrl: 'nextflix/videos/accidente',
      rankingUrl: 'nextflix/rankings/ranking5',
    },
  ],
}) satisfies Record<MovieType, Prisma.MovieCreateManyInput[]>

export const users = (<const>[
  { email: 'user1@example.com', password: 'Abc123*' },
  { email: 'user2@example.com', password: 'Xyz789*' },
]) satisfies Prisma.UserCreateManyInput[]
