import '@/styles/globals.css'
import type { Metadata } from 'next'
import { geistMono, geistSans } from '@/lib/constants'
import { cn } from '@/lib/utils'
import { Navigation } from '@/navigation'
import { Toaster, TooltipProvider } from '@/ui'

export const metadata: Metadata = {
  title: 'Nextflix - Netflix Clone',
  description: 'Netflix Clone generated by create next app',
  keywords: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Netflix Clone'],
  authors: { name: 'Esteban V.M.', url: 'https://github.com/esteban-vm' },
  generator: 'Next.js',
}

export default function RootLayout({ children }: WithChildren) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'dark relative h-screen min-h-[28rem] w-full antialiased',
          geistSans.variable,
          geistMono.variable
        )}
        suppressHydrationWarning
      >
        <TooltipProvider>
          <Navigation />
          {children}
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  )
}

const geistSans = localFont({
  src: '../public/fonts/geist-sans.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})

const geistMono = localFont({
  src: '../public/fonts/geist-mono.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})
