import '@/styles/globals.css'
import type { Metadata } from 'next'
import { Navigation } from '@/components/navigation'
import { Toaster, TooltipProvider } from '@/components/ui'
import { geistMono, geistSans } from '@/lib/constants'
import { cn } from '@/lib/utils'

export const metadata: Metadata = {
  title: 'Nextflix - Netflix Clone',
  description: 'Netflix Clone generated by create next app',
  keywords: ['Next.js', 'React', 'Tailwind CSS', 'TypeScript', 'Netflix Clone'],
  authors: { name: 'Esteban V.M.', url: 'https://github.com/esteban-vm' },
  generator: 'Next.js',
}

export default function RootLayout({ children }: Props.WithChildren) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'dark relative h-screen min-h-[28rem] w-full antialiased bg-background',
          geistSans.variable,
          geistMono.variable
        )}
        suppressHydrationWarning
      >
        <TooltipProvider>
          <Navigation />
          {children}
          <Toaster />
        </TooltipProvider>
      </body>
    </html>
  )
}
